sonar.projectKey=CacaoTrace
sonar.projectName=CacaoTrace
sonar.projectVersion=1.0

sonar.sources=app,run.py
sonar.tests=tests

sonar.host.url=http://localhost:9000

sonar.sourceEncoding=UTF-8
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/.venv/**,**/__pycache__/**,**/migrations/**,**/uploads/**,**/static/vendor/**,**/*.pyc
sonar.coverage.exclusions=app/templates/**,app/static/**,run.py
